/* i18n — Internationalization Module */
const I18n = (() => {
  let currentLang = 'en';
  const translations = {
    en: {
      authTagline: 'AI-Powered Study Assistant', loginTitle: 'Log In', signupTitle: 'Create Account', username: 'Username', password: 'Password', confirmPassword: 'Confirm Password', loginBtn: 'Log In', signupBtn: 'Create Account', noAccount: "Don't have an account?", signUpLink: 'Sign Up', haveAccount: 'Already have an account?', loginLink: 'Log In', loginError: 'Invalid username or password', signupErrorMatch: 'Passwords do not match', signupErrorExists: 'Username already exists', signupErrorShort: 'Password must be at least 4 characters',
      navDashboard: 'Dashboard', navSummarizer: 'Summarize Notes', navQuiz: 'Generate Quiz', navFlashcards: 'Flashcards', navTimer: 'Study Timer', navProgress: 'Progress', navHistory: 'Study History', navLeaderboard: 'Leaderboard', navAchievements: 'Achievements', navSettings: 'Settings', navGames: 'Study Games', navPatchNotes: 'Patch Notes', navCredits: 'Credits', logout: 'Logout',
      dashTitle: 'Dashboard', dashSubtitle: "Welcome back! Here's your study overview.", streakTitle: '{n} Day Study Streak!', streakMsg: 'Keep it up! Study today to maintain your streak.', streakMsgZero: 'Start studying today to begin your streak!', level: 'Level', xpProgress: 'XP: {current} / {next}', quizzesCompleted: 'Quizzes Completed', flashcardsReviewed: 'Flashcards Reviewed', totalStudyTime: 'Study Time (min)', achievementsUnlocked: 'Achievements', quickAccess: 'Quick Access', summarizeNotes: 'Summarize Notes', summarizeDesc: 'Paste your notes and get a summary', generateQuiz: 'Generate Quiz', quizDesc: 'Create quizzes from your notes', flashcards: 'Flashcards', flashcardsDesc: 'Create and flip through flashcards', studyTimer: 'Study Timer', timerDesc: 'Focus with Pomodoro timer', progressTracker: 'Progress Tracker', progressDesc: 'Track your study progress', studyGames: 'Study Games', gamesDesc: 'Learn through interactive games',
      summarizerTitle: 'AI Note Summarizer', summarizerSubtitle: 'Paste your notes and get an instant summary with key points.', pasteNotes: 'Paste your notes here...', summarizeBtn: 'Summarize Notes', summaryLabel: 'Summary', keyPoints: 'Key Points', keyConcepts: 'Key Concepts',
      importGoogleDoc: 'Import from Google Docs', importGoogleSlides: 'Import from Google Slides', importPlaceholder: 'Paste the public share link...', importBtn: 'Import', importError: 'Could not import. Make sure the link is a public Google Docs or Slides share link.', importSuccess: 'Content imported successfully!',
      quizTitle: 'Quiz Generator', quizSubtitle: 'Paste your notes to generate a multiple-choice quiz.', generateQuizBtn: 'Generate Quiz', quizPasteNotes: 'Paste your study notes here to generate a quiz...', quizScore: 'Score: {score} / {total}', quizComplete: 'Quiz Complete!', newQuiz: 'New Quiz', nextQuestion: 'Next Question', questionOf: 'Question {n} of {total}',
      flashcardsTitle: 'Flashcards', flashcardsSubtitle: 'Create flashcards from your notes and study them.', flashcardPaste: 'Paste your notes to generate flashcards...', generateCards: 'Generate Flashcards', clickToFlip: 'Click to flip', previous: 'Previous', next: 'Next', shuffle: 'Shuffle', cardOf: 'Card {n} of {total}',
      timerTitle: 'Study Timer', timerSubtitle: 'Use the Pomodoro technique to stay focused.', focusSession: 'Focus Session', breakTime: 'Break Time', start: 'Start', pause: 'Pause', reset: 'Reset', resume: 'Resume', sessionComplete: 'Session complete! Take a break.', breakComplete: 'Break over! Ready to focus?',
      progressTitle: 'Study Progress', progressSubtitle: 'Track your overall study activity and statistics.', notesSum: 'Notes Summarized', quizzesDone: 'Quizzes Done', flashcardsStudied: 'Flashcards Studied', studyMinutes: 'Study Minutes', currentStreak: 'Current Streak', days: 'days', progressOverview: 'Progress Overview',
      historyTitle: 'Study History', historySubtitle: 'A log of all your study activities.', noHistory: 'No study activity yet. Start studying to see your history!', today: 'Today', yesterday: 'Yesterday', daysAgo: '{n} days ago', summarized: 'Summarized Notes', completedQuiz: 'Completed Quiz', reviewedFlashcards: 'Reviewed Flashcards', timerSession: 'Timer Session', earnedXP: '+{n} XP', playedGame: 'Played Study Game',
      leaderboardTitle: 'Leaderboard', leaderboardSubtitle: 'See how you rank against other students.', allTime: 'All Time', weekly: 'Weekly', lbMotivation: 'Climb the leaderboard by studying every day! Keep your streak alive to stay on top! 🚀', owner: 'OWNER',
      achievementsTitle: 'Achievements', achievementsSubtitle: 'Unlock badges by completing study milestones.', achievementUnlocked: 'Achievement Unlocked!', unlocked: 'UNLOCKED', locked: 'LOCKED',
      badgeFirstSteps: 'First Steps', badgeFirstStepsDesc: 'Complete your first study activity', badgeQuizMaster: 'Quiz Master', badgeQuizMasterDesc: 'Complete 10 quizzes', badgeFlashcardExpert: 'Flashcard Expert', badgeFlashcardExpertDesc: 'Review 100 flashcards', badgeConsistency: 'Consistency King', badgeConsistencyDesc: 'Maintain a 7-day streak', badgeWarrior: 'Study Warrior', badgeWarriorDesc: 'Study for 10 hours total', badgeLegend: 'Streak Legend', badgeLegendDesc: 'Maintain a 30-day streak', badgeScholar: 'Quick Scholar', badgeScholarDesc: 'Summarize 20 sets of notes', badgeTimeLord: 'Time Lord', badgeTimeLordDesc: 'Complete 50 timer sessions',
      badgeNightOwl: 'Night Owl', badgeNightOwlDesc: 'Study after midnight', badgeSpeedDemon: 'Speed Demon', badgeSpeedDemonDesc: 'Complete 5 quizzes in one session', badgeSocialite: 'Social Learner', badgeSocialiteDesc: 'Reach top 3 on the leaderboard', badgeGamer: 'Study Gamer', badgeGamerDesc: 'Play 10 study games', badgeMarathon: 'Marathon Runner', badgeMarathonDesc: 'Study for 5 hours in one day', badgePerfectScore: 'Perfect Score', badgePerfectScoreDesc: 'Get 100% on a quiz', badgeVeteran: 'Veteran', badgeVeteranDesc: 'Use StudyCore for 30 days', badgePolyglot: 'Polyglot', badgePolyglotDesc: 'Switch languages 5 times',
      gamesTitle: 'Study Games', gamesSubtitle: 'Learn through fun interactive games.', wordScramble: 'Word Scramble', wordScrambleDesc: 'Unscramble study-related words', memoryMatch: 'Memory Match', memoryMatchDesc: 'Match pairs of study concepts', typeAnswer: 'Type your answer...', checkAnswer: 'Check', correct: 'Correct! 🎉', incorrect: 'Try again!', nextWord: 'Next Word', newGame: 'New Game', matchComplete: 'All pairs matched!', gamesPlayed: 'Games Played',
      creditsTitle: 'Credits', creditsSubtitle: 'The people behind StudyCore.', developedBy: 'Developed by', creditsDesc: 'StudyCore was designed and developed with <span style="color:#e74c3c">❤</span> as a modern study platform to help students learn more effectively.',
      patchNotesTitle: 'Patch Notes', patchNotesSubtitle: 'See what\'s new in StudyCore.',
      settingsTitle: 'Settings', settingsSubtitle: 'Customize your StudyCore experience.', language: 'Language', profile: 'Profile', dataManagement: 'Data Management', clearAllData: 'Clear All Data', clearDataConfirm: 'Are you sure? This will delete all your progress.', dangerZone: 'Danger Zone',
      sAppearance: 'Appearance', sTheme: 'Theme', sThemeDefault: 'Default Dark', sThemeMidnight: 'Midnight', sThemeAmoled: 'AMOLED Black', sFontSize: 'Font Size', sFontSmall: 'Small', sFontMedium: 'Medium', sFontLarge: 'Large', sAnimations: 'Animations',
      sTimerSettings: 'Timer Settings', sFocusDuration: 'Focus Duration', sBreakDuration: 'Break Duration', sTimerSound: 'Timer Sound',
      sNotifications: 'Notifications', sXPPopups: 'XP Popups', sAchievementPopups: 'Achievement Popups', sStreakReminder: 'Streak Reminder',
      sExportData: 'Export Data', sExport: 'Download JSON', sImportData: 'Import Data', sImport: 'Upload JSON', sResetStreak: 'Reset Streak', sReset: 'Reset', sResetConfirm: 'Are you sure? This will reset your streak to 0.',
      sDeleteAccount: 'Delete Account', sDelete: 'Delete', sDeleteConfirm: 'Are you sure? This will permanently delete your account and all data.',
      sChangePassword: 'Change Password', sCurrentPw: 'Current Password', sNewPw: 'New Password', sConfirmPw: 'Confirm New Password', sChangePwBtn: 'Update Password', sPwChanged: '✅ Password changed!', sWrongPassword: 'Current password is incorrect', sAllFieldsRequired: 'All fields are required',
      navNotes: 'Saved Notes', navChat: 'Chat',
      sAIIntegration: 'AI Integration', sAIDesc: 'Add your free Google Gemini API key to enable AI-powered quizzes and summaries. Get your key at ai.google.dev', sGeminiKey: 'Gemini API Key', sGeminiKeyPlaceholder: 'Paste your API key here...', sAIActive: 'AI is active',
      sFirebase: 'Firebase Backend', sFirebaseDesc: 'Add your Firebase Realtime Database config to enable global cross-device chat and a true global leaderboard.', sFirebaseConfig: 'Firebase Config JSON', sSaveFirebase: 'Connect Firebase', sFirebaseActive: 'Firebase Connected', sFirebaseError: 'Connection Failed', sFirebaseInvalid: 'Invalid JSON format',
      sMadeWith: 'Made with <span style="color:#e74c3c">❤</span> by'
    }, sv: {
      authTagline: 'AI-Driven Studieassistent', loginTitle: 'Logga In', signupTitle: 'Skapa Konto', username: 'Användarnamn', password: 'Lösenord', confirmPassword: 'Bekräfta Lösenord', loginBtn: 'Logga In', signupBtn: 'Skapa Konto', noAccount: 'Har du inget konto?', signUpLink: 'Registrera dig', haveAccount: 'Har du redan ett konto?', loginLink: 'Logga In', loginError: 'Ogiltigt användarnamn eller lösenord', signupErrorMatch: 'Lösenorden matchar inte', signupErrorExists: 'Användarnamnet finns redan', signupErrorShort: 'Lösenordet måste vara minst 4 tecken',
      navDashboard: 'Instrumentpanel', navSummarizer: 'Sammanfatta Anteckningar', navQuiz: 'Skapa Quiz', navFlashcards: 'Flashkort', navTimer: 'Studietimer', navProgress: 'Framsteg', navHistory: 'Studiehistorik', navLeaderboard: 'Topplista', navAchievements: 'Utmärkelser', navSettings: 'Inställningar', navGames: 'Studiespel', navPatchNotes: 'Uppdateringar', navCredits: 'Tack', logout: 'Logga Ut',
      dashTitle: 'Instrumentpanel', dashSubtitle: 'Välkommen tillbaka! Här är din studieöversikt.', streakTitle: '{n} Dagars Studiesvit!', streakMsg: 'Fortsätt så! Studera idag för att behålla din svit.', streakMsgZero: 'Börja studera idag för att starta din svit!', level: 'Nivå', xpProgress: 'XP: {current} / {next}', quizzesCompleted: 'Quiz Avklarade', flashcardsReviewed: 'Flashkort Granskade', totalStudyTime: 'Studietid (min)', achievementsUnlocked: 'Utmärkelser', quickAccess: 'Snabbåtkomst', summarizeNotes: 'Sammanfatta Anteckningar', summarizeDesc: 'Klistra in anteckningar och få en sammanfattning', generateQuiz: 'Skapa Quiz', quizDesc: 'Skapa quiz från dina anteckningar', flashcards: 'Flashkort', flashcardsDesc: 'Skapa och bläddra bland flashkort', studyTimer: 'Studietimer', timerDesc: 'Fokusera med Pomodoro-timer', progressTracker: 'Framstegsmätare', progressDesc: 'Följ dina studiefremsteg', studyGames: 'Studiespel', gamesDesc: 'Lär dig genom interaktiva spel',
      summarizerTitle: 'AI Anteckningssammanfattare', summarizerSubtitle: 'Klistra in dina anteckningar och få en snabb sammanfattning.', pasteNotes: 'Klistra in dina anteckningar här...', summarizeBtn: 'Sammanfatta Anteckningar', summaryLabel: 'Sammanfattning', keyPoints: 'Nyckelpunkter', keyConcepts: 'Nyckelbegrepp',
      importGoogleDoc: 'Importera från Google Docs', importGoogleSlides: 'Importera från Google Slides', importPlaceholder: 'Klistra in den publika delningslänken...', importBtn: 'Importera', importError: 'Kunde inte importera. Kontrollera att länken är en offentlig Google Docs/Slides-länk.', importSuccess: 'Innehåll importerat!',
      quizTitle: 'Quizgenerator', quizSubtitle: 'Klistra in dina anteckningar för att skapa ett flervals-quiz.', generateQuizBtn: 'Skapa Quiz', quizPasteNotes: 'Klistra in dina studieanteckningar här...', quizScore: 'Resultat: {score} / {total}', quizComplete: 'Quiz Klart!', newQuiz: 'Nytt Quiz', nextQuestion: 'Nästa Fråga', questionOf: 'Fråga {n} av {total}',
      flashcardsTitle: 'Flashkort', flashcardsSubtitle: 'Skapa flashkort från dina anteckningar.', flashcardPaste: 'Klistra in anteckningar för att skapa flashkort...', generateCards: 'Skapa Flashkort', clickToFlip: 'Klicka för att vända', previous: 'Föregående', next: 'Nästa', shuffle: 'Blanda', cardOf: 'Kort {n} av {total}',
      timerTitle: 'Studietimer', timerSubtitle: 'Använd Pomodoro-tekniken för att hålla fokus.', focusSession: 'Fokuspass', breakTime: 'Paustid', start: 'Starta', pause: 'Pausa', reset: 'Återställ', resume: 'Fortsätt', sessionComplete: 'Pass klart! Ta en paus.', breakComplete: 'Pausen är slut! Redo att fokusera?',
      progressTitle: 'Studiefremsteg', progressSubtitle: 'Följ din studieaktivitet och statistik.', notesSum: 'Sammanfattade Anteckningar', quizzesDone: 'Quiz Avklarade', flashcardsStudied: 'Flashkort Studerade', studyMinutes: 'Studieminuter', currentStreak: 'Nuvarande Svit', days: 'dagar', progressOverview: 'Framstegsöversikt',
      historyTitle: 'Studiehistorik', historySubtitle: 'En logg över alla dina studieaktiviteter.', noHistory: 'Ingen studieaktivitet ännu. Börja studera!', today: 'Idag', yesterday: 'Igår', daysAgo: '{n} dagar sedan', summarized: 'Sammanfattade Anteckningar', completedQuiz: 'Avklarade Quiz', reviewedFlashcards: 'Granskade Flashkort', timerSession: 'Timerpass', earnedXP: '+{n} XP', playedGame: 'Spelade Studiespel',
      leaderboardTitle: 'Topplista', leaderboardSubtitle: 'Se hur du rankas mot andra studenter.', allTime: 'Alla Tider', weekly: 'Veckovis', lbMotivation: 'Klättra på topplistan genom att studera varje dag! Håll din svit vid liv! 🚀', owner: 'ÄGARE',
      achievementsTitle: 'Utmärkelser', achievementsSubtitle: 'Lås upp märken genom att nå studiemål.', achievementUnlocked: 'Utmärkelse Upplåst!', unlocked: 'UPPLÅST', locked: 'LÅST',
      badgeFirstSteps: 'Första Stegen', badgeFirstStepsDesc: 'Slutför din första studieaktivitet', badgeQuizMaster: 'Quizmästare', badgeQuizMasterDesc: 'Slutför 10 quiz', badgeFlashcardExpert: 'Flashkortsexpert', badgeFlashcardExpertDesc: 'Granska 100 flashkort', badgeConsistency: 'Konsistenskung', badgeConsistencyDesc: 'Håll en 7-dagars svit', badgeWarrior: 'Studiekrigare', badgeWarriorDesc: 'Studera i 10 timmar totalt', badgeLegend: 'Svitlegend', badgeLegendDesc: 'Håll en 30-dagars svit', badgeScholar: 'Snabb Lärling', badgeScholarDesc: 'Sammanfatta 20 anteckningar', badgeTimeLord: 'Tidsherre', badgeTimeLordDesc: 'Slutför 50 timerpass',
      badgeNightOwl: 'Nattuggla', badgeNightOwlDesc: 'Studera efter midnatt', badgeSpeedDemon: 'Snabbdemon', badgeSpeedDemonDesc: 'Slutför 5 quiz på en session', badgeSocialite: 'Social Lärare', badgeSocialiteDesc: 'Nå topp 3 på topplistan', badgeGamer: 'Studiespelare', badgeGamerDesc: 'Spela 10 studiespel', badgeMarathon: 'Maratonlöpare', badgeMarathonDesc: 'Studera i 5 timmar på en dag', badgePerfectScore: 'Perfekt Resultat', badgePerfectScoreDesc: 'Få 100% på ett quiz', badgeVeteran: 'Veteran', badgeVeteranDesc: 'Använd StudyCore i 30 dagar', badgePolyglot: 'Polyglot', badgePolyglotDesc: 'Byt språk 5 gånger',
      gamesTitle: 'Studiespel', gamesSubtitle: 'Lär dig genom roliga interaktiva spel.', wordScramble: 'Ordpussel', wordScrambleDesc: 'Blanda om studierelaterade ord', memoryMatch: 'Minnespar', memoryMatchDesc: 'Matcha par av studiebegrepp', typeAnswer: 'Skriv ditt svar...', checkAnswer: 'Kontrollera', correct: 'Rätt! 🎉', incorrect: 'Försök igen!', nextWord: 'Nästa Ord', newGame: 'Nytt Spel', matchComplete: 'Alla par matchade!', gamesPlayed: 'Spel Spelade',
      creditsTitle: 'Tack', creditsSubtitle: 'Personerna bakom StudyCore.', developedBy: 'Utvecklad av', creditsDesc: 'StudyCore designades och utvecklades med <span style="color:#e74c3c">❤</span> som en modern studieplattform för att hjälpa studenter att lära sig mer effektivt.',
      patchNotesTitle: 'Uppdateringar', patchNotesSubtitle: 'Se vad som är nytt i StudyCore.',
      settingsTitle: 'Inställningar', settingsSubtitle: 'Anpassa din StudyCore-upplevelse.', language: 'Språk', profile: 'Profil', dataManagement: 'Datahantering', clearAllData: 'Radera All Data', clearDataConfirm: 'Är du säker? Detta raderar alla dina framsteg.', dangerZone: 'Farozon',
      sAppearance: 'Utseende', sTheme: 'Tema', sThemeDefault: 'Standard Mörk', sThemeMidnight: 'Midnatt', sThemeAmoled: 'AMOLED Svart', sFontSize: 'Textstorlek', sFontSmall: 'Liten', sFontMedium: 'Medel', sFontLarge: 'Stor', sAnimations: 'Animeringar',
      sTimerSettings: 'Timerinställningar', sFocusDuration: 'Fokustid', sBreakDuration: 'Paustid', sTimerSound: 'Timerljud',
      sNotifications: 'Aviseringar', sXPPopups: 'XP-popup', sAchievementPopups: 'Utmärkelsepopup', sStreakReminder: 'Svitpåminnelse',
      sExportData: 'Exportera Data', sExport: 'Ladda ner JSON', sImportData: 'Importera Data', sImport: 'Ladda upp JSON', sResetStreak: 'Återställ Svit', sReset: 'Återställ', sResetConfirm: 'Är du säker? Detta återställer din svit till 0.',
      sDeleteAccount: 'Radera Konto', sDelete: 'Radera', sDeleteConfirm: 'Är du säker? Detta raderar permanent ditt konto och all data.',
      sChangePassword: 'Ändra Lösenord', sCurrentPw: 'Nuvarande Lösenord', sNewPw: 'Nytt Lösenord', sConfirmPw: 'Bekräfta Nytt Lösenord', sChangePwBtn: 'Uppdatera Lösenord', sPwChanged: '✅ Lösenordet ändrat!', sWrongPassword: 'Nuvarande lösenord är felaktigt', sAllFieldsRequired: 'Alla fält krävs',
      navNotes: 'Sparade Anteckningar', navChat: 'Chatt',
      sAIIntegration: 'AI-Integration', sAIDesc: 'Lägg till din gratis Google Gemini API-nyckel för AI-drivna quiz och sammanfattningar. Hämta din nyckel på ai.google.dev', sGeminiKey: 'Gemini API-Nyckel', sGeminiKeyPlaceholder: 'Klistra in din API-nyckel här...', sAIActive: 'AI är aktiv',
      sFirebase: 'Firebase-Backend', sFirebaseDesc: 'Lägg till din Firebase Realtime Database-konfig för att aktivera global chatt och en global topplista.', sFirebaseConfig: 'Firebase Konfig JSON', sSaveFirebase: 'Anslut Firebase', sFirebaseActive: 'Firebase Ansluten', sFirebaseError: 'Anslutning Misslyckades', sFirebaseInvalid: 'Ogiltigt JSON-format',
      sMadeWith: 'Gjord med <span style="color:#e74c3c">❤</span> av'
    }
  };

  function t(key, params = {}) {
    let text = translations[currentLang]?.[key] || translations['en']?.[key] || key;
    Object.entries(params).forEach(([k, v]) => { text = text.replace(`{${k}}`, v); });
    return text;
  }
  function setLang(lang) { currentLang = lang; localStorage.setItem('sc_lang', lang); updateDOM(); }
  function getLang() { return currentLang; }
  function init() { const s = localStorage.getItem('sc_lang'); if (s && translations[s]) currentLang = s; }
  function updateDOM() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.placeholder = t(key);
      else el.textContent = t(key);
    });
    const langBtn = document.getElementById('lang-btn');
    if (langBtn) langBtn.textContent = `🌐 ${currentLang.toUpperCase()}`;
  }
  return { t, setLang, getLang, init, updateDOM };
})();
