/* i18n — Internationalization Module */
const I18n = (() => {
  let currentLang = 'en';
  const translations = { en: {
    authTagline:'AI-Powered Study Assistant',loginTitle:'Log In',signupTitle:'Create Account',username:'Username',password:'Password',confirmPassword:'Confirm Password',loginBtn:'Log In',signupBtn:'Create Account',noAccount:"Don't have an account?",signUpLink:'Sign Up',haveAccount:'Already have an account?',loginLink:'Log In',loginError:'Invalid username or password',signupErrorMatch:'Passwords do not match',signupErrorExists:'Username already exists',signupErrorShort:'Password must be at least 4 characters',
    navDashboard:'Dashboard',navSummarizer:'Summarize Notes',navQuiz:'Generate Quiz',navFlashcards:'Flashcards',navTimer:'Study Timer',navProgress:'Progress',navHistory:'Study History',navLeaderboard:'Leaderboard',navAchievements:'Achievements',navSettings:'Settings',logout:'Logout',
    dashTitle:'Dashboard',dashSubtitle:"Welcome back! Here's your study overview.",streakTitle:'{n} Day Study Streak!',streakMsg:'Keep it up! Study today to maintain your streak.',streakMsgZero:'Start studying today to begin your streak!',level:'Level',xpProgress:'XP: {current} / {next}',quizzesCompleted:'Quizzes Completed',flashcardsReviewed:'Flashcards Reviewed',totalStudyTime:'Study Time (min)',achievementsUnlocked:'Achievements',quickAccess:'Quick Access',summarizeNotes:'Summarize Notes',summarizeDesc:'Paste your notes and get a summary',generateQuiz:'Generate Quiz',quizDesc:'Create quizzes from your notes',flashcards:'Flashcards',flashcardsDesc:'Create and flip through flashcards',studyTimer:'Study Timer',timerDesc:'Focus with Pomodoro timer',progressTracker:'Progress Tracker',progressDesc:'Track your study progress',
    summarizerTitle:'AI Note Summarizer',summarizerSubtitle:'Paste your notes and get an instant summary with key points.',pasteNotes:'Paste your notes here...',summarizeBtn:'Summarize Notes',summaryLabel:'Summary',keyPoints:'Key Points',keyConcepts:'Key Concepts',
    quizTitle:'Quiz Generator',quizSubtitle:'Paste your notes to generate a multiple-choice quiz.',generateQuizBtn:'Generate Quiz',quizPasteNotes:'Paste your study notes here to generate a quiz...',quizScore:'Score: {score} / {total}',quizComplete:'Quiz Complete!',newQuiz:'New Quiz',nextQuestion:'Next Question',questionOf:'Question {n} of {total}',
    flashcardsTitle:'Flashcards',flashcardsSubtitle:'Create flashcards from your notes and study them.',flashcardPaste:'Paste your notes to generate flashcards...',generateCards:'Generate Flashcards',clickToFlip:'Click to flip',previous:'Previous',next:'Next',shuffle:'Shuffle',cardOf:'Card {n} of {total}',
    timerTitle:'Study Timer',timerSubtitle:'Use the Pomodoro technique to stay focused.',focusSession:'Focus Session',breakTime:'Break Time',start:'Start',pause:'Pause',reset:'Reset',resume:'Resume',sessionComplete:'Session complete! Take a break.',breakComplete:'Break over! Ready to focus?',
    progressTitle:'Study Progress',progressSubtitle:'Track your overall study activity and statistics.',notesSum:'Notes Summarized',quizzesDone:'Quizzes Done',flashcardsStudied:'Flashcards Studied',studyMinutes:'Study Minutes',currentStreak:'Current Streak',days:'days',progressOverview:'Progress Overview',
    historyTitle:'Study History',historySubtitle:'A log of all your study activities.',noHistory:'No study activity yet. Start studying to see your history!',today:'Today',yesterday:'Yesterday',daysAgo:'{n} days ago',summarized:'Summarized Notes',completedQuiz:'Completed Quiz',reviewedFlashcards:'Reviewed Flashcards',timerSession:'Timer Session',earnedXP:'+{n} XP',
    leaderboardTitle:'Leaderboard',leaderboardSubtitle:'See how you rank against other students.',allTime:'All Time',weekly:'Weekly',lbMotivation:'Climb the leaderboard by studying every day! Keep your streak alive to stay on top! 🚀',
    achievementsTitle:'Achievements',achievementsSubtitle:'Unlock badges by completing study milestones.',achievementUnlocked:'Achievement Unlocked!',unlocked:'UNLOCKED',locked:'LOCKED',
    badgeFirstSteps:'First Steps',badgeFirstStepsDesc:'Complete your first study activity',badgeQuizMaster:'Quiz Master',badgeQuizMasterDesc:'Complete 10 quizzes',badgeFlashcardExpert:'Flashcard Expert',badgeFlashcardExpertDesc:'Review 100 flashcards',badgeConsistency:'Consistency King',badgeConsistencyDesc:'Maintain a 7-day streak',badgeWarrior:'Study Warrior',badgeWarriorDesc:'Study for 10 hours total',badgeLegend:'Streak Legend',badgeLegendDesc:'Maintain a 30-day streak',badgeScholar:'Quick Scholar',badgeScholarDesc:'Summarize 20 sets of notes',badgeTimeLord:'Time Lord',badgeTimeLordDesc:'Complete 50 timer sessions',
    settingsTitle:'Settings',settingsSubtitle:'Customize your StudyCore experience.',language:'Language',profile:'Profile',dataManagement:'Data Management',clearAllData:'Clear All Data',clearDataConfirm:'Are you sure? This will delete all your progress.',dangerZone:'Danger Zone'
  }, sv: {
    authTagline:'AI-Driven Studieassistent',loginTitle:'Logga In',signupTitle:'Skapa Konto',username:'Användarnamn',password:'Lösenord',confirmPassword:'Bekräfta Lösenord',loginBtn:'Logga In',signupBtn:'Skapa Konto',noAccount:'Har du inget konto?',signUpLink:'Registrera dig',haveAccount:'Har du redan ett konto?',loginLink:'Logga In',loginError:'Ogiltigt användarnamn eller lösenord',signupErrorMatch:'Lösenorden matchar inte',signupErrorExists:'Användarnamnet finns redan',signupErrorShort:'Lösenordet måste vara minst 4 tecken',
    navDashboard:'Instrumentpanel',navSummarizer:'Sammanfatta Anteckningar',navQuiz:'Skapa Quiz',navFlashcards:'Flashkort',navTimer:'Studietimer',navProgress:'Framsteg',navHistory:'Studiehistorik',navLeaderboard:'Topplista',navAchievements:'Utmärkelser',navSettings:'Inställningar',logout:'Logga Ut',
    dashTitle:'Instrumentpanel',dashSubtitle:'Välkommen tillbaka! Här är din studieöversikt.',streakTitle:'{n} Dagars Studiesvit!',streakMsg:'Fortsätt så! Studera idag för att behålla din svit.',streakMsgZero:'Börja studera idag för att starta din svit!',level:'Nivå',xpProgress:'XP: {current} / {next}',quizzesCompleted:'Quiz Avklarade',flashcardsReviewed:'Flashkort Granskade',totalStudyTime:'Studietid (min)',achievementsUnlocked:'Utmärkelser',quickAccess:'Snabbåtkomst',summarizeNotes:'Sammanfatta Anteckningar',summarizeDesc:'Klistra in anteckningar och få en sammanfattning',generateQuiz:'Skapa Quiz',quizDesc:'Skapa quiz från dina anteckningar',flashcards:'Flashkort',flashcardsDesc:'Skapa och bläddra bland flashkort',studyTimer:'Studietimer',timerDesc:'Fokusera med Pomodoro-timer',progressTracker:'Framstegsmätare',progressDesc:'Följ dina studiefremsteg',
    summarizerTitle:'AI Anteckningssammanfattare',summarizerSubtitle:'Klistra in dina anteckningar och få en snabb sammanfattning.',pasteNotes:'Klistra in dina anteckningar här...',summarizeBtn:'Sammanfatta Anteckningar',summaryLabel:'Sammanfattning',keyPoints:'Nyckelpunkter',keyConcepts:'Nyckelbegrepp',
    quizTitle:'Quizgenerator',quizSubtitle:'Klistra in dina anteckningar för att skapa ett flervals-quiz.',generateQuizBtn:'Skapa Quiz',quizPasteNotes:'Klistra in dina studieanteckningar här...',quizScore:'Resultat: {score} / {total}',quizComplete:'Quiz Klart!',newQuiz:'Nytt Quiz',nextQuestion:'Nästa Fråga',questionOf:'Fråga {n} av {total}',
    flashcardsTitle:'Flashkort',flashcardsSubtitle:'Skapa flashkort från dina anteckningar.',flashcardPaste:'Klistra in anteckningar för att skapa flashkort...',generateCards:'Skapa Flashkort',clickToFlip:'Klicka för att vända',previous:'Föregående',next:'Nästa',shuffle:'Blanda',cardOf:'Kort {n} av {total}',
    timerTitle:'Studietimer',timerSubtitle:'Använd Pomodoro-tekniken för att hålla fokus.',focusSession:'Fokuspass',breakTime:'Paustid',start:'Starta',pause:'Pausa',reset:'Återställ',resume:'Fortsätt',sessionComplete:'Pass klart! Ta en paus.',breakComplete:'Pausen är slut! Redo att fokusera?',
    progressTitle:'Studiefremsteg',progressSubtitle:'Följ din studieaktivitet och statistik.',notesSum:'Sammanfattade Anteckningar',quizzesDone:'Quiz Avklarade',flashcardsStudied:'Flashkort Studerade',studyMinutes:'Studieminuter',currentStreak:'Nuvarande Svit',days:'dagar',progressOverview:'Framstegsöversikt',
    historyTitle:'Studiehistorik',historySubtitle:'En logg över alla dina studieaktiviteter.',noHistory:'Ingen studieaktivitet ännu. Börja studera!',today:'Idag',yesterday:'Igår',daysAgo:'{n} dagar sedan',summarized:'Sammanfattade Anteckningar',completedQuiz:'Avklarade Quiz',reviewedFlashcards:'Granskade Flashkort',timerSession:'Timerpass',earnedXP:'+{n} XP',
    leaderboardTitle:'Topplista',leaderboardSubtitle:'Se hur du rankas mot andra studenter.',allTime:'Alla Tider',weekly:'Veckovis',lbMotivation:'Klättra på topplistan genom att studera varje dag! Håll din svit vid liv! 🚀',
    achievementsTitle:'Utmärkelser',achievementsSubtitle:'Lås upp märken genom att nå studiemål.',achievementUnlocked:'Utmärkelse Upplåst!',unlocked:'UPPLÅST',locked:'LÅST',
    badgeFirstSteps:'Första Stegen',badgeFirstStepsDesc:'Slutför din första studieaktivitet',badgeQuizMaster:'Quizmästare',badgeQuizMasterDesc:'Slutför 10 quiz',badgeFlashcardExpert:'Flashkortsexpert',badgeFlashcardExpertDesc:'Granska 100 flashkort',badgeConsistency:'Konsistenskung',badgeConsistencyDesc:'Håll en 7-dagars svit',badgeWarrior:'Studiekrigare',badgeWarriorDesc:'Studera i 10 timmar totalt',badgeLegend:'Svitlegend',badgeLegendDesc:'Håll en 30-dagars svit',badgeScholar:'Snabb Lärling',badgeScholarDesc:'Sammanfatta 20 anteckningar',badgeTimeLord:'Tidsherre',badgeTimeLordDesc:'Slutför 50 timerpass',
    settingsTitle:'Inställningar',settingsSubtitle:'Anpassa din StudyCore-upplevelse.',language:'Språk',profile:'Profil',dataManagement:'Datahantering',clearAllData:'Radera All Data',clearDataConfirm:'Är du säker? Detta raderar alla dina framsteg.',dangerZone:'Farozon'
  }};

  function t(key, params = {}) {
    let text = translations[currentLang]?.[key] || translations['en']?.[key] || key;
    Object.entries(params).forEach(([k, v]) => { text = text.replace(`{${k}}`, v); });
    return text;
  }
  function setLang(lang) { currentLang = lang; localStorage.setItem('sc_lang', lang); updateDOM(); }
  function getLang() { return currentLang; }
  function init() { const s = localStorage.getItem('sc_lang'); if (s && translations[s]) currentLang = s; }
  function updateDOM() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.placeholder = t(key);
      else el.textContent = t(key);
    });
    const langBtn = document.getElementById('lang-btn');
    if (langBtn) langBtn.textContent = `🌐 ${currentLang.toUpperCase()}`;
  }
  return { t, setLang, getLang, init, updateDOM };
})();
